# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      fail-fast: true
      matrix:
        neovim_branch: ['v0.6.0', 'master']

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      NEOVIM_BRANCH: ${{ matrix.neovim_branch }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup build dependencies
        run: |
          sudo apt update &&
          sudo apt install -y \
            autoconf \
            automake \
            cmake \
            g++ \
            gettext \
            gperf \
            libjemalloc-dev \
            libluajit-5.1-dev \
            libmsgpack-dev \
            libtermkey-dev \
            libtool \
            libtool-bin \
            libunibilium-dev \
            libvterm-dev \
            lua-bitop \
            lua-lpeg \
            lua-mpack \
            ninja-build \
            pkg-config \
            unzip

      - name: Cache neovim
        uses: actions/cache@v2
        with:
          path: neovim-${{env.NEOVIM_BRANCH}}
          key: build-${{env.NEOVIM_BRANCH}}

      - name: Build Neovim
        run: make neovim NEOVIM_BRANCH=$NEOVIM_BRANCH

      - name: Run Test
        run: make test
